// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBu0SaDzndXZmPnVBPyl-ta3_1K0hRyYcA',
//     appId: '1:111654178933:web:19f9f3d2d20c23d3d3e83c',
//     messagingSenderId: '111654178933',
//     projectId: 'uniarchive-1e8be',
//     authDomain: 'uniarchive-1e8be.firebaseapp.com',
//     storageBucket: 'uniarchive-1e8be.firebasestorage.app',
//     measurementId: 'G-19QECPJKV0',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBjwTaull0ZGjPTs-JTNTOIFjB-skTMYy8',
//     appId: '1:111654178933:android:f3df2bd8c6d15d2ad3e83c',
//     messagingSenderId: '111654178933',
//     projectId: 'uniarchive-1e8be',
//     storageBucket: 'uniarchive-1e8be.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD0xLJtx_Ks35KfU-y1Inro_gZCtuBNBEI',
//     appId: '1:111654178933:ios:1455e463cef22762d3e83c',
//     messagingSenderId: '111654178933',
//     projectId: 'uniarchive-1e8be',
//     storageBucket: 'uniarchive-1e8be.firebasestorage.app',
//     iosBundleId: 'com.example.uniarchive',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyD0xLJtx_Ks35KfU-y1Inro_gZCtuBNBEI',
//     appId: '1:111654178933:ios:1455e463cef22762d3e83c',
//     messagingSenderId: '111654178933',
//     projectId: 'uniarchive-1e8be',
//     storageBucket: 'uniarchive-1e8be.firebasestorage.app',
//     iosBundleId: 'com.example.uniarchive',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBu0SaDzndXZmPnVBPyl-ta3_1K0hRyYcA',
//     appId: '1:111654178933:web:6aa6b64eab56fad3d3e83c',
//     messagingSenderId: '111654178933',
//     projectId: 'uniarchive-1e8be',
//     authDomain: 'uniarchive-1e8be.firebaseapp.com',
//     storageBucket: 'uniarchive-1e8be.firebasestorage.app',
//     measurementId: 'G-Y598WQ2M91',
//   );

// }